version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  Flask-Workflow:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - run: pip install requirements.txt

      - run: pytest

  